-- Miden Assembly instruction reference: { name, description, stack effect }.
-- Immediate-operand variants keep the metadata's `{n}` placeholders.
--
-- GENERATED FILE -- regenerate with scripts/gen_instructions.py from the
-- instruction metadata in Trail of Bits' masm-lsp (MIT licensed), itself
-- derived from the official Miden instruction reference:
--   https://github.com/trailofbits/masm-lsp
--   crates/masm-instructions/data/instruction_reference.toml

-- stylua: ignore
local instructions = {
  { "lte", "c = 1, if a ≤ b, and 0 otherwise.", "(b, a, ...) → (a ≤ b, ...)" },
  { "lte.{n}", "c = 1, if a ≤ {n}, and 0 otherwise.", "(a, ...) → (a ≤ {n}, ...)" },
  { "lt", "c = 1, if a < b, and 0 otherwise.", "(b, a, ...) → (a < b, ...)" },
  { "lt.{n}", "c = 1, if a < {n}, and 0 otherwise.", "(a, ...) → (a < {n}, ...)" },
  { "gte", "c = 1, if a ≥ b, and 0 otherwise.", "(b, a, ...) → (a ≥ b, ...)" },
  { "gte.{n}", "c = 1, if a ≥ {n}, and 0 otherwise.", "(b, a, ...) → (a ≥ {n}, ...)" },
  { "gt", "c = 1, if a > b, and 0 otherwise.", "(b, a, ...) → (a > b, ...)" },
  { "gt.{n}", "c = 1, if a > {n}, and 0 otherwise.", "(a, ...) → (a > {n}, ...)" },
  { "eq", "c = 1, if a = b, and 0 otherwise.", "(b, a, ...) → (a = b, ...)" },
  { "eq.{n}", "c = 1, if a = {n}, and 0 otherwise.", "(a, ...) → (a = {n}, ...)" },
  { "neq", "c = 1, if a ≠ b, and 0 otherwise.", "(b, a, ...) → (a ≠ b, ...)" },
  { "neq.{n}", "c = 1, if a ≠ {n}, and 0 otherwise.", "(a, ...) → (a ≠ {n}, ...)" },
  { "eqw", "c = 1, if a_i = b_i for all i in {0,1,2,3}, and 0 otherwise.", "(A, B, ...) → (A = B, A, B, ...)" },
  { "is_odd", "b = 1, if a is odd, and 0 otherwise.", "(a, ...) → (a & 1, ...)" },
  { "assert", "Removes a if a = 1. Fails if a ≠ 1.", "(a, ...) → (...)" },
  { "assertz", "Removes a if a = 0. Fails if a ≠ 0.", "(a, ...) → (...)" },
  { "assert_eq", "Removes a, b if a = b. Fails if a ≠ b.", "(b, a, ...) → (...)" },
  { "assert_eqw", "Removes A, B if A = B. Fails if A ≠ B.", "(B, A, ...) → (...)" },
  { "add", "c = (a + b) mod p.", "(b, a, ...) → (a + b, ...)" },
  { "add.{n}", "c = (a + {n}) mod p", "(a, ...) → (a + {n}, ...)" },
  { "sub", "c = (a - b) mod p.", "(b, a, ...) → (a - b, ...)" },
  { "sub.{n}", "c = (a - {n}) mod p.", "(a, ...) → (a - {n}, ...)" },
  { "mul", "c = (a * b) mod p.", "(b, a, ...) → (a * b, ...)" },
  { "mul.{n}", "c = (a * {n}) mod p.", "(a, ...) → (a * {n}, ...)" },
  { "div", "c = (a * b^-1) mod p.", "(b, a, ...) → (a / b, ...)" },
  { "div.{n}", "c = (a * {n}^-1) mod p.", "(a, ...) → ( a / {n}, ...)" },
  { "neg", "b = -a mod p.", "(a, ...) → (-a, ...)" },
  { "inv", "b = a^-1 mod p.", "(a, ...) → (a^-1, ...)" },
  { "pow2", "b = 2^a. Fails if a > 63.", "(a, ...) → (2^a, ...)" },
  { "exp.u{n}", "c = a^b. Fails if {n} is outside [0, 63)", "(b, a, ...) → (a^b, ...)" },
  { "exp.{n}", "c = a^b. Fails if {n} is outside [0, 63)", "(b, a, ...) → (a^b, ...)" },
  { "ilog2", "b = ⌊log_2(a)⌋. Fails if a = 0.", "(a, ...) → (⌊log_2(a)⌋, ...)" },
  { "not", "b = 1 - a. Fails if a > 1.", "(a, ...) → (1 - a, ...)" },
  { "and", "c = a * b. Fails if max(a, b) > 1.", "(b, a, ...) → (a and b, ...)" },
  { "or", "c = a + b - a * b. Fails if max(a, b) > 1.", "(b, a, ...) → (a or b, ...)" },
  { "xor", "c = a + b - 2 * a * b. Fails if max(a, b) > 1.", "(b, a, ...) → (a xor b, ...)" },
  { "ext2add", "c1 = (a1 + b1) mod p ; c0 = (a0 + b0) mod p", "(b1, b0, a1, a0, ...) → (a1 + b1, a0 + b0, ...)" },
  { "ext2sub", "c1 = (a1 - b1) mod p ; c0 = (a0 - b0) mod p", "(b1, b0, a1, a0, ...) → (a1 - b1, a0 - b0, ...)" },
  { "ext2mul", "c1 = (a0 + a1)(b0 + b1) - a0b0 mod p ; c0 = a0b0 - 2a1b1 mod p", "(b1, b0, a1, a0, ...) → (c1, c0, ...)" },
  { "ext2neg", "c1 = -a1 ; c0 = -a0", "(a1, a0, ...) → (-a1, -a0, ...)" },
  { "ext2inv", "c = a^-1 in F_p[x]/(x^2 - x + 2). Fails if a = 0.", "(a1, a0, ...) → (c1, c0, ...)" },
  { "ext2div", "c = a * b^-1 in F_p[x]/(x^2 - x + 2). Fails if b = 0.", "(b1, b0, a1, a0, ...) → (c1, c0, ...)" },
  { "u32test", "b = 1, if a < 2^32, and 0 otherwise.", "(a, ...) → (a < 2^32, a, ...)" },
  { "u32testw", "b = 1, if a_i < 2^32 for all i in {0,1,2,3}, and 0 otherwise.", "(A, ...) → (b, A, ...)" },
  { "u32assert", "Fails if a ≥ 2^32.", "(a, ...) → (a, ...)" },
  { "u32assert2", "Fails if a ≥ 2^32 or b ≥ 2^32.", "(b, a,...) → (b, a,...)" },
  { "u32assertw", "Fails if any element of A is ≥ 2^32.", "(A, ...) → (A, ...)" },
  { "u32cast", "b = a mod 2^32.", "(a, ...) → (a mod 2^32, ...)" },
  { "u32split", "b = a mod 2^32, c = ⌊a / 2^32⌋", "(a, ...) → (⌊a / 2^32⌋, a mod 2^32, ...)" },
  { "u32overflowing_add", "c = (a + b) mod 2^32, d = 1, if (a + b) ≥ 2^32, and 0 otherwise. . Undefined if max(a, b) ≥ 2^32.", "(b, a, ...) → (overflow, (a + b) mod 2^32, ...)" },
  { "u32overflowing_add.{n}", "c = (a + {n}) mod 2^32, d = 1, if (a + {n}) ≥ 2^32, and 0 otherwise. . Undefined if max(a, b) ≥ 2^32.", "(a, ...) → (overflow, (a + {n}) mod 2^32, ...)" },
  { "u32wrapping_add", "c = (a + b) mod 2^32. Undefined if max(a, b) ≥ 2^32.", "(b, a, ...) → ((a + b) mod 2^32, ...)" },
  { "u32wrapping_add.{n}", "c = (a + {n}) mod 2^32. Undefined if max(a, b) ≥ 2^32.", "(a, ...) → ((a + {n}) mod 2^32, ...)" },
  { "u32overflowing_add3", "d = (a+b+c) mod 2^32, e = ⌊(a+b+c) / 2^32⌋. Undefined if max(a,b,c) ≥ 2^32.", "(c, b, a, ...) → (⌊(a+b+c) / 2^32⌋, (a+b+c) mod 2^32, ...)" },
  { "u32wrapping_add3", "d = (a+b+c) mod 2^32. Undefined if max(a,b,c) ≥ 2^32.", "(c, b, a, ...) → ((a+b+c) mod 2^32, ...)" },
  { "u32overflowing_sub", "c = (a - b) mod 2^32, d = 1, if a < b, and 0 otherwise. . Undefined if max(a, b) ≥ 2^32.", "(b, a, ...) → (overflow, (a - b) mod 2^32, ...)" },
  { "u32overflowing_sub.{n}", "c = (a - {n}) mod 2^32, d = 1, if a < b, and 0 otherwise. . Undefined if max(a, b) ≥ 2^32.", "(a, ...) → (overflow, (a - {n}) mod 2^32, ...)" },
  { "u32wrapping_sub", "c = (a - b) mod 2^32. Undefined if max(a, b) ≥ 2^32.", "(b, a, ...) → ((a - b) mod 2^32, ...)" },
  { "u32wrapping_sub.{n}", "c = (a - {n}) mod 2^32. Undefined if max(a, b) ≥ 2^32.", "(a, ...) → ((a - {n}) mod 2^32, ...)" },
  { "u32overflowing_mul", "c = (a * b) mod 2^32, d = ⌊(a * b) / 2^32⌋. Undefined if max(a, b) ≥ 2^32.", "(b, a, ...) → (⌊(a * b) / 2^32⌋, (a * b) mod 2^32, ...)" },
  { "u32overflowing_mul.{n}", "c = (a * {n}) mod 2^32, d = ⌊(a * b) / 2^32⌋. Undefined if max(a, b) ≥ 2^32.", "(a, ...) → (⌊(a * {n}) / 2^32⌋, (a * {n}) mod 2^32, ...)" },
  { "u32wrapping_mul", "c = (a * b) mod 2^32. Undefined if max(a, b) ≥ 2^32.", "(b, a, ...) → ((a * b) mod 2^32, ...)" },
  { "u32wrapping_mul.{n}", "c = (a * {n}) mod 2^32. Undefined if max(a, b) ≥ 2^32.", "(a, ...) → ((a * {n}) mod 2^32, ...)" },
  { "u32overflowing_madd", "d = (a * b + c) mod 2^32, e = ⌊(a * b + c) / 2^32⌋. Undefined if max(a,b,c) ≥ 2^32.", "(b, a, c, ...) → (⌊(a * b + c) / 2^32⌋, (a * b + c) mod 2^32, ...)" },
  { "u32wrapping_madd", "d = (a * b+c) mod 2^32. Undefined if max(a,b,c) ≥ 2^32.", "(b, a, c, ...) → ((a * b + c) mod 2^32, ...)" },
  { "u32div", "c = ⌊a / b⌋. Fails if b = 0. Undefined if max(a, b) ≥ 2^32.", "(b, a, ...) → (⌊a / b⌋, ...)" },
  { "u32div.{n}", "c = ⌊a / {n}⌋. Fails if {n} = 0. Undefined if max(a, {n}) ≥ 2^32.", "(a, ...) → (⌊a / b⌋, ...)" },
  { "u32mod", "c = a mod b. Fails if b = 0. Undefined if max(a, b) ≥ 2^32.", "(b, a, ...) → (a mod b, ...)" },
  { "u32mod.{n}", "c = a mod {n}. Fails if {n} = 0. Undefined if max(a, {n}) ≥ 2^32.", "(a, ...) → (a mod {n}, ...)" },
  { "u32divmod", "c = ⌊a / b⌋, d = a mod b. Fails if b = 0. Undefined if max(a, b) ≥ 2^32.", "(b, a, ...) → (a mod b, ⌊a / b⌋, ...)" },
  { "u32divmod.{n}", "c = ⌊a / {n}⌋, d = a mod {n}. Fails if {n} = 0. Undefined if max(a, {n}) ≥ 2^32.", "(a, ...) → (a mod {n}, ⌊a / {n}⌋, ...)" },
  { "u32and", "Bitwise AND. Fails if max(a, b) ≥ 2^32.", "(b, a, ...) → (a bitand b, ...)" },
  { "u32and.{n}", "Bitwise AND. Fails if max(a, {n}) ≥ 2^32.", "(b, a, ...) → (a bitand {n}, ...)" },
  { "u32or", "Bitwise OR. Fails if max(a, b) ≥ 2^32.", "(b, a, ...) → (a bitor b, ...)" },
  { "u32or.{n}", "Bitwise OR. Fails if max(a, {n}) ≥ 2^32.", "(a, ...) → (a bitor {n}, ...)" },
  { "u32xor", "Bitwise XOR. Fails if max(a, b) ≥ 2^32.", "(b, a, ...) → (a bitxor b, ...)" },
  { "u32xor.{n}", "Bitwise XOR. Fails if max(a, {n}) ≥ 2^32.", "(b, a, ...) → (a bitxor {n}, ...)" },
  { "u32not", "Bitwise NOT. Fails if a ≥ 2^32.", "(a, ...) → (~a, ...)" },
  { "u32not.{n}", "Bitwise NOT. Fails if a ≥ 2^32.", "(a, ...) → (~a, ...)" },
  { "u32shl", "c = (a * 2^b) mod 2^32. Undefined if a ≥ 2^32 or b > 31.", "(b, a, ...) → (a << b, ...)" },
  { "u32shl.{n}", "c = (a * 2^{n}) mod 2^32. Undefined if a ≥ 2^32 or {n} > 31.", "(a, ...) → (a << {n}, ...)" },
  { "u32shr", "c = floor(a / 2^b). Undefined if a ≥ 2^32 or b > 31.", "(b, a, ...) → (a >> b, ...)" },
  { "u32shr.{n}", "c = floor(a / 2^b). Undefined if a ≥ 2^32 or b > 31.", "(a, ...) → (a >> {n}, ...)" },
  { "u32rotl", "Rotate left. Undefined if a ≥ 2^32 or b > 31.", "(b, a, ...) → (rotl(a, b), ...)" },
  { "u32rotl.{n}", "Rotate left. Undefined if a ≥ 2^32 or {n} > 31.", "(a, ...) → (rotl(a, {n}), ...)" },
  { "u32rotr", "Rotate right. Undefined if a ≥ 2^32 or b > 31.", "(b, a, ...) → (rotr(a, b), ...)" },
  { "u32rotr.{n}", "Rotate right. Undefined if a ≥ 2^32 or b > 31.", "(a, ...) → (rotr(a, {n}), ...)" },
  { "u32popcnt", "Population count (Hamming weight). Undefined if a ≥ 2^32.", "(a, ...) → (popcount(a), ...)" },
  { "u32clz", "Count leading zeros. Undefined if a ≥ 2^32.", "(a, ...) → (clz(a), ...)" },
  { "u32ctz", "Count trailing zeros. Undefined if a ≥ 2^32.", "(a, ...) → (ctz(a), ...)" },
  { "u32clo", "Count leading ones. Undefined if a ≥ 2^32.", "(a, ...) → (clo(a), ...)" },
  { "u32cto", "Count trailing ones. Undefined if a ≥ 2^32.", "(a, ...) → (cto(a), ...)" },
  { "u32lt", "c = 1, if a < b, and 0 otherwise. Undefined if max(a, b) ≥ 2^32.", "(b, a, ...) → (a < b, ...)" },
  { "u32lt.{n}", "c = 1, if a < {n}, and 0 otherwise. Undefined if max(a, {n}) ≥ 2^32.", "(a, ...) → (a < {n}, ...)" },
  { "u32lte", "c = 1, if a ≤ b, and 0 otherwise. Undefined if max(a, b) ≥ 2^32.", "(b, a, ...) → (a ≤ b, ...)" },
  { "u32lte.{n}", "c = 1, if a ≤ {n}, and 0 otherwise. Undefined if max(a, b) ≥ 2^32.", "(a, ...) → (a ≤ {n}, ...)" },
  { "u32gt", "c = 1, if a > b, and 0 otherwise. Undefined if max(a, b) ≥ 2^32.", "(b, a, ...) → (a > b, ...)" },
  { "u32gt.{n}", "c = 1, if a > {n}, and 0 otherwise. Undefined if max(a, b) ≥ 2^32.", "(a, ...) → (a > {n}, ...)" },
  { "u32gte", "c = 1, if a ≥ b, and 0 otherwise. Undefined if max(a, b) ≥ 2^32.", "(b, a, ...) → (a ≥ b, ...)" },
  { "u32gte.{n}", "c = 1, if a ≥ {n}, and 0 otherwise. Undefined if max(a, b) ≥ 2^32.", "(a, ...) → (a ≥ {n}, ...)" },
  { "u32min", "c = min(a, b). Undefined if max(a, b) ≥ 2^32.", "(b, a, ...) → (min(a, b), ...)" },
  { "u32min.{n}", "c = min(a, {n}). Undefined if max(a, {n}) ≥ 2^32.", "(a, ...) → (min(a, {n}), ...)" },
  { "u32max", "c = max(a, b). Undefined if max(a, b) ≥ 2^32.", "(b, a, ...) → (max(a, b), ...)" },
  { "u32max.{n}", "c = max(a, {n}). Undefined if max(a, {n}) ≥ 2^32.", "(a, ...) → (max(a, {n}), ...)" },
  { "drop", "Deletes the top stack item.", "(a, ...) → (...)" },
  { "dropw", "Deletes a word (4 elements) from the top of the stack.", "(A, ...) → (...)" },
  { "padw", "Pushes four 0 values onto the stack.", "(...) → (0, 0, 0, 0, ...)" },
  { "dup.{n}", "Pushes a copy of the {nth} stack item (0-indexed) onto the stack.", "(..., a, ...) → (a, ..., a, ...)" },
  { "dupw.{n}", "Pushes a copy of the {nth} stack word (0-indexed) onto the stack.", "(..., A, ...) → (A, ..., A, ...)" },
  { "swap.{n}", "Swaps the top stack item with the {nth} stack item (1-indexed).", "(a, ..., b, ...) → (b, ..., a, ...)" },
  { "swapw.{n}", "Swaps the top stack word with the {nth} stack word (1-indexed).", "(A, ..., B, ...) → (B, ..., A, ...)" },
  { "swapdw", "Swaps words: 1st with 3rd, 2nd with 4th.", "(D, C, B, A, ...) → (B, A, D, C, ...)" },
  { "movup.{n}", "Moves the {nth} stack item (2-indexed) to the top.", "(..., a, ...) → (a, ...)" },
  { "movupw.{n}", "Moves the {nth} stack word (2-indexed) to the top.", "(..., A, ...) → (A, ...)" },
  { "movdn.{n}", "Moves the top stack item to the {nth} position (2-indexed).", "(a, ...) → (..., a, ...)" },
  { "movdnw.{n}", "Moves the top stack word to the {nth} word position (2-indexed).", "(A, ...) → (..., A, ...)" },
  { "cswap", "If c = 1, d = b, e = a. If c = 0, d = a, e = b. Fails if c > 1.", "(c, b, a, ...) → (c ? a : b, c ? b : a, ...)" },
  { "cswapw", "If c = 1, D = B, E = A. If c = 0, D = A, E = B. Fails if c > 1.", "(c, B, A, ...) → (c ? A : B, c ? B : A, ...)" },
  { "cdrop", "If c = 1, d = b. If c = 0, d = a. Fails if c > 1.", "(c, b, a, ...) → (c ? b : a, ...)" },
  { "cdropw", "If c = 1, D = B. If c = 0, D = A. Fails if c > 1.", "(c, B, A, ...) → (c ? B : A, ...)" },
  { "push.{n}", "Pushes {n} onto the stack.", "(...) → ({n}, ...)" },
  { "clk", "Pushes current clock cycle t.", "(...) → (t, ...)" },
  { "sdepth", "Pushes current stack depth d.", "(...) → (d, ...)" },
  { "caller", "In context 0, overwrites the top 4 stack items with hash H of the function that syscalled into the current context.", "(A, ...) → (H, ...)" },
  { "locaddr.{n}", "Pushes absolute memory address a of local memory at index {n}.", "(...) → (a, ...)" },
  { "procref.{n}", "Pushes MAST root A of procedure {n}.", "(...) → (A, ...)" },
  { "adv_push.{n}", "Pops {n} values from advice stack to operand stack (1st popped is deepest).", "(...) → (a, ...)" },
  { "adv_loadw", "Pops word A (4 elements) from advice stack, overwrites top word of operand stack.", "(B, ...) → (A, ...)" },
  { "adv_pipe", "Pops 2 words (D, E) from advice stack. Overwrites top 2 words of operand stack. Writes (D, E) to memory at a and a + 1. b ← a + 2.", "(C, B, A, a, ...) → (E, D, A, b,...)" },
  { "adv.push_mapval", "Pushes values from advice_map[K] to advice stack.", "(...) → (...)" },
  { "adv.push_mapvaln", "Pushes (n, a1, a2, ...) from advice_map[K] to advice stack, where n is element count.", "(...) → (...)" },
  { "adv.push_mtnode", "Pushes Merkle tree node (root R, depth d, index i) from Merkle store to advice stack.", "(d, i, R, ...) → (d, i, R, ...)" },
  { "adv.insert_mem", "advice_map[K] ← mem[a..b].", "(K, a, b, ...) → (K, a, b, ...)" },
  { "adv.insert_hdword", "K ← hash(A || B, domain=0). advice_map[K] ← (A, B).", "(B, A, ...) → (B, A, ...)" },
  { "adv.insert_hdword_d", "K ← hash(A || B, domain=d). advice_map[K] ← (A, B).", "(B, A, d, ...) → (B, A, d, ...)" },
  { "adv.insert_hqword", "K ← hash(hash(hash(A || B) || C) || D), domain = 0. advice_map[K] ← (A, B, C, D).", "(D, C, B, A, ...) → (D, C, B, A, ...)" },
  { "adv.insert_hperm", "K ← permute(C, A, B).digest. advice_map[K] ← (A, B).", "(B, A, C, ...) → (B, A, C, ...)" },
  { "mem_load", "v ← mem[a]. Pushes element from mem[a] and pops a.", "(a, ...) → (mem[a], ...)" },
  { "mem_load.{n}", "v ← mem[{n}]. Pushes element from mem[{n}].", "(a, ...) → (mem[{n}], ...)" },
  { "mem_loadw_be", "A ← mem[a..a+3] (word, big-endian). Overwrites top 4 stack elements (mem[a+3] is top). If a on stack, it's popped.", "(a, A,...) → (mem[a..a+3], ...)" },
  { "mem_loadw_be.{n}", "A ← mem[{n}..{n+3}] (word, big-endian). Overwrites top 4 stack elements (mem[a+3] is top).", "(A, ...) → (mem[{n}..{n+3}], ...)" },
  { "mem_loadw_le", "A ← mem[a..a+3] (word, little-endian). Overwrites top 4 stack elements (mem[a] is top). If a on stack, it's popped.", "(a, A,...) → (mem[a..a+3], ...)" },
  { "mem_loadw_le.{n}", "A ← mem[{n}..{n+3}] (word, little-endian). Overwrites top 4 stack elements (mem[a] is top).", "(A, ...) → (mem[{n}..{n+3}], ...)" },
  { "mem_store", "mem[a] ← v. Pops v to mem[a]. If a on stack, it's popped.", "(a, v, ...) → (...)" },
  { "mem_store.{n}", "mem[{n}] ← v. Pops v to mem[{n}].", "(v, ...) → (...)" },
  { "mem_storew_be", "mem[a..a+3] ← A. Stores word A in big-endian order (top stack element at mem[a+3]). If a on stack, it's popped.", "(a, A, ...) → (A, ...)" },
  { "mem_storew_be.{n}", "mem[{n}..{n+3}] ← A. Stores word A in big-endian order (top stack element at mem[{n+3}]).", "(A, ...) → (A, ...)" },
  { "mem_storew_le", "mem[a..a+3] ← A. Stores word A in little-endian order (top stack element at mem[a]). If a on stack, it's popped.", "(a, A, ...) → (A, ...)" },
  { "mem_storew_le.{n}", "mem[{n}..{n+3}] ← A. Stores word A in little-endian order (top stack element at mem[{n}]).", "(A, ...) → (A, ...)" },
  { "mem_stream", "(E, D) ← (mem[a..a+3], mem[a+4..a+7]). b ← a + 8. Reads 2 sequential words from memory to top of stack.", "(C, B, A, a, ...) → (E, D, A, b, ...)" },
  { "loc_load.{n}", "v ← local[{n}]. Pushes element from local memory at index {n}.", "(...) → (v, ...)" },
  { "loc_loadw_be.{n}", "B ← local[{n}..{n+3}]. Reads word in big-endian order, local[{n+3}] is top of stack.", "(A, ...) → (B, ...)" },
  { "loc_loadw_le.{n}", "B ← local[{n}..{n+3}]. Reads word in little-endian order, local[{n}] is top of stack.", "(A, ...) → (B, ...)" },
  { "loc_store.{n}", "local[i] ← v. Pops v to local memory at index {n}.", "(v, ...) → (...)" },
  { "loc_storew_be.{n}", "local[{n}..{n+3}] ← A. Stores word in big-endian order, top stack element at local[{n+3}].", "(A, ...) → (A, ...)" },
  { "loc_storew_le.{n}", "local[{n}..{n+3}] ← A. Stores word in little-endian order, top stack element at local[{n}].", "(A, ...) → (A, ...)" },
  { "hash", "B ← hash(A). 1-to-1 Rescue Prime Optimized hash.", "(A, ...) → (hash(A), ...)" },
  { "hperm", "D, E, F ← permute(C, A, B). Rescue Prime Optimized permutation. C = capacity, A,B = rate, E = digest.", "(B, A, C, ...) → (F, E, D, ...)" },
  { "hmerge", "C ← hash(A, B). 2-to-1 Rescue Prime Optimized hash.", "(B, A, ...) → (hash(A, B), ...)" },
  { "mtree_get", "Verifies Merkle path for node V at depth d, index i for tree R (from advice provider), returns V.", "(d, i, R, ...) → (V, R, ...)" },
  { "mtree_set", "Updates node in tree R1 at depth d, index i to V2. Returns old value V1 and new root R2. Both trees in advice provider.", "(d, i, R1, V2, ...) → (V1, R2, ...)" },
  { "mtree_merge", "Merges Merkle trees with roots L (left) and R (right) into new tree M. Input trees retained.", "(R, L, ...) → (M, ...)" },
  { "mtree_verify", "Verifies Merkle path for node V at depth d, index i for tree R (from advice provider).", "(V, d, i, R, ...) → (V, d, i, R, ...)" },
  { "emit.{n}", "Emits the event {n} to the host.", "(...) → (...)" },
  { "emit", "Emits an event using the event_id from the top of the stack.", "(event_id, ...) → (event_id, ...)" },
  { "trace.{n}", "Emits the trace {n} to the host.", "(...) → (...)" },
  { "log_precompile", "Absorbs a precompile commitment into the transcript used for deferred verification.", "(COMM, TAG, PAD, ...) → (R1, R0, CAP_NEXT, ...)" },
}

-- Reference gaps (mnemonics the metadata lacks but arity.lua simulates)
-- are filled from the hand-maintained instructions_extra.lua; the
-- generator emits this merge, so regeneration cannot lose them.
for _, e in ipairs(require("masm.instructions_extra")) do
  instructions[#instructions + 1] = e
end
return instructions
